language: python

python:
    - "2.7"
    - "3.3"

install:
    - python setup.py --quiet install

script:
    - mkdir -p .tmp
    - rm -f .tmp/*
    - superzippy --output=.tmp/foo "git+file://$PWD" superzippy.packaging:run
    - .tmp/foo --help
